import { localePath, type Locale } from "@/lib/i18n";

// Blog posts. Body blocks keep the markup simple and translatable.
export type Block = { type: "p"; text: string } | { type: "h2"; text: string } | { type: "ul"; items: string[] };
export type Post = {
  slug: string;
  category: string;
  title: string;
  excerpt: string;
  author: string;
  date: string; // ISO
  readMinutes: number;
  body: Block[];
};

const en: Post[] = [
  {
    slug: "using-ai-to-study",
    category: "Study techniques",
    title: "Using AI to study, the right way",
    excerpt: "AI can explain, quiz and guide you. It works best when you use it to understand, not to skip the thinking.",
    author: "Note Swift Academic Team",
    date: "2026-09-18",
    readMinutes: 5,
    body: [
      { type: "p", text: "AI tools can be a good study partner. They can explain a concept in a different way, break a problem into steps, or help you check whether you really understood a chapter. Used badly, they do your thinking for you, and that shows up on exam day." },
      { type: "h2", text: "Ask for explanations, not just answers" },
      { type: "p", text: "Instead of asking for the final answer, ask why each step happens. When the explanation makes sense, close the chat and try a similar question on your own. If you get stuck again, go back and ask about the exact step that confused you." },
      { type: "ul", items: ["Ask: why does this step work?", "Ask for a simpler example before the hard one.", "Explain the idea back in your own words and ask whether you got it right."] },
      { type: "h2", text: "Keep the conversation inside your syllabus" },
      { type: "p", text: "Generic AI tools do not know what your board expects. In the Note Swift app, SikAI works inside your course: you choose the subject and the module, and it answers in that context. That keeps explanations close to what NEB and CDC actually ask, instead of drifting into university-level detail." },
      { type: "h2", text: "Use it alongside lessons, not instead of them" },
      { type: "p", text: "Watch the lesson and read the notes first. Use AI when something still does not click. Your syllabus and your teachers decide what matters for the exam, so treat AI as a patient tutor, not a replacement for the lesson." },
      { type: "h2", text: "Turn explanations into practice" },
      { type: "p", text: "Understanding is only half the job. After a concept makes sense, attempt chapter tests and MCQs to check that it sticks. A question generator for SikAI is coming soon to Note Swift; until then, use the chapter tests in the Test tab." },
      { type: "h2", text: "A simple rule" },
      { type: "p", text: "If you could not solve the same question tomorrow without help, you have not learned it yet. Use AI to get there, then prove it to yourself." },
    ],
  },
  {
    slug: "see-preparation",
    category: "SEE preparation",
    title: "How to prepare for SEE without burning out",
    excerpt: "A simple, chapter-by-chapter plan for the months before SEE, and how to use your weak topics to your advantage.",
    author: "Note Swift Academic Team",
    date: "2026-08-27",
    readMinutes: 6,
    body: [
      { type: "p", text: "SEE preparation is not about studying the most hours. It is about covering the right things, in the right order, and checking yourself often. Students who burn out usually study long but without a plan." },
      { type: "h2", text: "Build a weekly rhythm" },
      { type: "ul", items: ["Learn new chapters on weekdays: one lesson and its notes per session.", "Practise every day with 10 to 15 MCQs or short questions.", "Take one chapter test at the end of each week.", "Use Saturday to revisit the topics where you lost marks."] },
      { type: "p", text: "A rhythm matters more than a perfect timetable. When every week has the same shape, you spend less energy deciding what to do and more energy doing it." },
      { type: "h2", text: "Start from the specification grid" },
      { type: "p", text: "The CDC specification grid shows how marks are spread across each paper. Chapters that carry more marks deserve more practice. Check the grid for Compulsory Mathematics, Science and Social Studies before you plan your months." },
      { type: "h2", text: "Use previous year questions early" },
      { type: "p", text: "Many students save PYQs for the last month. Try them earlier. They show you how questions are actually asked, which changes how you read the chapter in the first place." },
      { type: "h2", text: "Turn weak topics into easy marks" },
      { type: "p", text: "Keep a short list of topics where you lose marks. Revisit one of them every Saturday. A weak topic that you fix in February is worth more than a strong topic you revise for the fifth time." },
      { type: "h2", text: "Protect your sleep" },
      { type: "p", text: "Memory needs rest. A tired brain reads the same page three times. Keep a fixed sleep time, especially in the final weeks, and avoid all-night study before exam days." },
      { type: "h2", text: "In the final month" },
      { type: "ul", items: ["Attempt one full paper per subject each week, timed.", "Revise from your own short notes and formula sheets.", "Practise writing answers neatly within the word limits."] },
    ],
  },
  {
    slug: "neb-class-12",
    category: "NEB preparation",
    title: "NEB Class 12: a realistic revision plan for the final three months",
    excerpt: "How to split your time between new topics, revision and full mock tests before the NEB board exams.",
    author: "Note Swift Academic Team",
    date: "2026-07-30",
    readMinutes: 7,
    body: [
      { type: "p", text: "Three months is enough time to prepare well for NEB Class 12, if you stop trying to do everything at once. Split the time into three clear phases." },
      { type: "h2", text: "Month one: close the gaps" },
      { type: "p", text: "List every chapter in each subject and mark it green, yellow or red based on how confident you feel. Spend this month turning reds into yellows. Watch the lessons again for red chapters and solve the examples yourself before reading the solutions." },
      { type: "h2", text: "Month two: practise under time" },
      { type: "p", text: "Move from reading to solving. Attempt chapter tests with a timer. Write down every question you got wrong and why: a concept gap, a calculation slip, or poor time use. Each needs a different fix." },
      { type: "ul", items: ["Science students: keep a daily set of numericals for Physics and Chemistry.", "Management students: practise full accounting problems, not only theory.", "Everyone: practise long answers with a clear structure."] },
      { type: "h2", text: "Month three: full papers" },
      { type: "ul", items: ["Attempt at least one full mock paper per subject each week.", "Review mistakes the same day, while they are fresh.", "Keep short formula and key-point sheets for the final days.", "Use NEB model questions to check you are covering every question type."] },
      { type: "h2", text: "Do not ignore the smaller subjects" },
      { type: "p", text: "English and Nepali carry the same weight on your transcript as your main subjects. Give them steady, short sessions every week instead of a last-minute rush." },
      { type: "h2", text: "The night before" },
      { type: "p", text: "Do not start a new topic. Read your short notes, check your admit card and materials, and sleep on time. Calm students recall more than tired ones." },
    ],
  },
  {
    slug: "see-to-class-11-science",
    category: "Career guidance",
    title: "Moving from SEE to Class 11 Science: what changes",
    excerpt: "Class 11 Science feels like a big jump. Here is what is different and how to settle in during your first term.",
    author: "Note Swift Academic Team",
    date: "2026-06-12",
    readMinutes: 5,
    body: [
      { type: "p", text: "Most students find the first few weeks of Class 11 Science difficult. That is normal. The syllabus is deeper, the pace is faster and the questions expect you to apply ideas, not just repeat them." },
      { type: "h2", text: "Concepts over memorisation" },
      { type: "p", text: "In SEE you could often score by remembering answers. In Class 11, questions test whether you understand why something works. Spend extra time on the first chapters of Physics and Chemistry, because later chapters build on them." },
      { type: "h2", text: "Numericals every day" },
      { type: "p", text: "Do a few numericals daily instead of many on the weekend. Consistency builds speed, and speed matters in board exams." },
      { type: "h2", text: "Revise your SEE mathematics" },
      { type: "p", text: "Algebra, trigonometry and basic geometry from Class 9 and 10 appear everywhere in Class 11 Physics and Mathematics. A week spent revising them early saves months of confusion." },
      { type: "h2", text: "Settle into a routine in the first term" },
      { type: "ul", items: ["Review each day's class within 24 hours.", "Keep one notebook per subject for formulas and solved examples.", "Ask doubts early, before they pile up."] },
      { type: "p", text: "The jump feels big for everyone. Students who build steady habits in the first term usually find the rest of +2 much easier." },
    ],
  },
  {
    slug: "specification-grid",
    category: "SEE preparation",
    title: "What is a specification grid, and how should you use it?",
    excerpt: "The specification grid shows how marks are spread across a paper. Here is how to read it and plan your practice around it.",
    author: "Note Swift Academic Team",
    date: "2026-05-21",
    readMinutes: 4,
    body: [
      { type: "p", text: "A specification grid, published by the Curriculum Development Centre for SEE and by NEB for Class 11 and 12, shows how marks are distributed across chapters, question types and skill levels in a paper. It is the closest thing you have to a map of the exam." },
      { type: "h2", text: "Why it matters" },
      { type: "p", text: "If a chapter carries many marks, it deserves more practice. If a topic usually appears as a long question, you should practise writing full answers, not just reading." },
      { type: "h2", text: "How to read it" },
      { type: "ul", items: ["Look at marks per chapter or unit first.", "Check the number of very short, short and long questions.", "Notice the split between knowledge, understanding, application and higher ability questions."] },
      { type: "h2", text: "How to use it" },
      { type: "ul", items: ["Print it or keep it on your phone next to your study plan.", "Tick off chapters as you complete lessons and tests.", "Use it to choose which PYQs to attempt first."] },
      { type: "p", text: "Specification grids for your subjects are available in the study resources inside the Note Swift app, organised by class." },
    ],
  },
  {
    slug: "active-recall",
    category: "Study techniques",
    title: "Active recall: the study habit that beats re-reading",
    excerpt: "Re-reading feels productive. Testing yourself actually is. A short guide to studying with active recall.",
    author: "Note Swift Academic Team",
    date: "2026-04-09",
    readMinutes: 4,
    body: [
      { type: "p", text: "Active recall means closing the book and trying to remember what you just learned. It is harder than re-reading, and that is exactly why it works. Every time you pull an idea out of memory, you make it easier to find next time." },
      { type: "h2", text: "Why re-reading misleads you" },
      { type: "p", text: "When you re-read a page, it feels familiar, and familiar feels like knowing. But recognising an answer is much easier than producing it in an exam hall." },
      { type: "h2", text: "Three ways to try it today" },
      { type: "ul", items: ["After each lesson, write down three key points from memory.", "Use MCQs and short questions right after studying a chapter.", "Explain a concept out loud as if teaching a friend."] },
      { type: "h2", text: "Combine it with spacing" },
      { type: "p", text: "Recall works best when you return to a topic after a gap: the next day, then after a week, then after a month. Short, spaced sessions beat one long session." },
      { type: "p", text: "In the Note Swift app, the chapter tests and daily practice in the Test tab are built for exactly this habit." },
    ],
  },
];

const ne: Post[] = [
  {
    slug: "using-ai-to-study",
    category: "अध्ययन विधि",
    title: "AI प्रयोग गरेर पढ्ने सही तरिका",
    excerpt: "AI ले बुझाउन, प्रश्न सोध्न र बाटो देखाउन सक्छ। सोच्ने काम छोड्न होइन, बुझ्नका लागि प्रयोग गर्दा यो सबैभन्दा उपयोगी हुन्छ।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-09-18",
    readMinutes: 5,
    body: [
      { type: "p", text: "AI उपकरणहरू राम्रा अध्ययन साथी बन्न सक्छन्। तिनले कुनै अवधारणा फरक तरिकाले बुझाउन, समस्यालाई चरणमा तोड्न वा तपाईंले अध्याय साँच्चै बुझ्नुभयो कि भनी जाँच्न मद्दत गर्छन्। तर गलत तरिकाले प्रयोग गर्दा तिनले तपाईंको सोच्ने काम आफैं गरिदिन्छन्, र त्यसको असर परीक्षाको दिन देखिन्छ।" },
      { type: "h2", text: "उत्तर मात्र होइन, व्याख्या सोध्नुहोस्" },
      { type: "p", text: "अन्तिम उत्तर माग्नुको सट्टा हरेक चरण किन हुन्छ भनेर सोध्नुहोस्। व्याख्या बुझेपछि च्याट बन्द गर्नुहोस् र त्यस्तै अर्को प्रश्न आफैं हल गर्नुहोस्। फेरि अड्किनुभयो भने अलमल पारेको ठ्याक्कै त्यही चरणबारे सोध्नुहोस्।" },
      { type: "ul", items: ["सोध्नुहोस्: यो चरणले किन काम गर्छ?", "कठिन प्रश्नअघि सजिलो उदाहरण माग्नुहोस्।", "कुरा आफ्नै शब्दमा फर्काएर भन्नुहोस् र ठीक बुझें कि भनी सोध्नुहोस्।"] },
      { type: "h2", text: "कुराकानी आफ्नो पाठ्यक्रमभित्रै राख्नुहोस्" },
      { type: "p", text: "सामान्य AI उपकरणलाई तपाईंको बोर्डले के अपेक्षा गर्छ थाहा हुँदैन। Note Swift एपमा SikAI तपाईंको कोर्सभित्रै काम गर्छ: तपाईं विषय र मोड्युल छान्नुहुन्छ, र यसले त्यही सन्दर्भमा उत्तर दिन्छ। यसले व्याख्यालाई विश्वविद्यालय स्तरका विवरणतिर नबहकाई NEB र CDC ले साँच्चै सोध्ने कुरासँग नजिक राख्छ।" },
      { type: "h2", text: "पाठको सट्टा होइन, पाठसँगै प्रयोग गर्नुहोस्" },
      { type: "p", text: "पहिले पाठ हेर्नुहोस् र नोट्स पढ्नुहोस्। त्यसपछि पनि केही कुरा नबुझिए AI प्रयोग गर्नुहोस्। परीक्षाका लागि के महत्वपूर्ण छ भन्ने तपाईंको पाठ्यक्रम र शिक्षकले तय गर्छन्, त्यसैले AI लाई धैर्यवान ट्युटरका रूपमा लिनुहोस्, पाठको विकल्पका रूपमा होइन।" },
      { type: "h2", text: "व्याख्यालाई अभ्यासमा बदल्नुहोस्" },
      { type: "p", text: "बुझ्नु आधा काम मात्र हो। अवधारणा बुझेपछि त्यो दिमागमा बस्यो कि भनी जाँच्न अध्याय परीक्षा र MCQ गर्नुहोस्। SikAI का लागि प्रश्न जेनेरेटर छिट्टै Note Swift मा आउँदैछ; त्यतिन्जेल Test ट्याबका अध्याय परीक्षा प्रयोग गर्नुहोस्।" },
      { type: "h2", text: "एउटा सजिलो नियम" },
      { type: "p", text: "भोलि त्यही प्रश्न कसैको मद्दतबिना हल गर्न सक्नुहुन्न भने तपाईंले अझै सिक्नुभएको छैन। त्यहाँसम्म पुग्न AI प्रयोग गर्नुहोस्, अनि आफैंलाई प्रमाणित गर्नुहोस्।" },
    ],
  },
  {
    slug: "see-preparation",
    category: "SEE तयारी",
    title: "नथाकी SEE को तयारी कसरी गर्ने",
    excerpt: "SEE अघिका महिनाहरूका लागि अध्याय अनुसारको सजिलो योजना, र आफ्ना कमजोर विषयलाई कसरी फाइदामा बदल्ने।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-08-27",
    readMinutes: 6,
    body: [
      { type: "p", text: "SEE को तयारी सबैभन्दा धेरै घण्टा पढ्ने कुरा होइन। सही कुरा, सही क्रममा पढ्ने र बारम्बार आफैंलाई जाँच्ने कुरा हो। थाकेर हार खाने विद्यार्थीहरू प्रायः लामो समय पढ्छन्, तर योजनाबिना।" },
      { type: "h2", text: "साप्ताहिक लय बनाउनुहोस्" },
      { type: "ul", items: ["हप्ताका दिनमा नयाँ अध्याय पढ्नुहोस्: एक सत्रमा एउटा पाठ र त्यसको नोट्स।", "हरेक दिन १० देखि १५ वटा MCQ वा छोटा प्रश्न अभ्यास गर्नुहोस्।", "हरेक हप्ताको अन्त्यमा एउटा अध्याय परीक्षा दिनुहोस्।", "अंक गुमाएका विषय दोहोर्याउन शनिबार प्रयोग गर्नुहोस्।"] },
      { type: "p", text: "उत्तम तालिकाभन्दा नियमित लय बढी महत्वपूर्ण हुन्छ। हरेक हप्ताको ढाँचा उस्तै हुँदा के गर्ने भनी सोच्न कम शक्ति खर्च हुन्छ र काम गर्न बढी।" },
      { type: "h2", text: "विशिष्टीकरण तालिकाबाट सुरु गर्नुहोस्" },
      { type: "p", text: "CDC को विशिष्टीकरण तालिकाले हरेक पत्रमा अंक कसरी बाँडिएको छ देखाउँछ। धेरै अंक बोक्ने अध्यायलाई बढी अभ्यास चाहिन्छ। महिनाको योजना बनाउनुअघि अनिवार्य गणित, विज्ञान र सामाजिक अध्ययनको तालिका हेर्नुहोस्।" },
      { type: "h2", text: "विगत वर्षका प्रश्न चाँडै हेर्नुहोस्" },
      { type: "p", text: "धेरै विद्यार्थी PYQ अन्तिम महिनाका लागि साँचेर राख्छन्। तिनलाई चाँडै प्रयास गर्नुहोस्। तिनले प्रश्न वास्तवमा कसरी सोधिन्छन् देखाउँछन्, जसले अध्याय पढ्ने तरिका नै बदलिदिन्छ।" },
      { type: "h2", text: "कमजोर विषयलाई सजिलो अंकमा बदल्नुहोस्" },
      { type: "p", text: "अंक गुमाउने विषयहरूको छोटो सूची राख्नुहोस्। हरेक शनिबार त्यसमध्ये एउटा दोहोर्याउनुहोस्। फागुनमा सुधारेको एउटा कमजोर विषय, पाँचौं पटक दोहोर्याएको बलियो विषयभन्दा बढी मूल्यवान हुन्छ।" },
      { type: "h2", text: "निद्रालाई जोगाउनुहोस्" },
      { type: "p", text: "स्मरणशक्तिलाई आराम चाहिन्छ। थाकेको दिमागले एउटै पृष्ठ तीन पटक पढ्छ। विशेषगरी अन्तिम हप्ताहरूमा सुत्ने समय निश्चित राख्नुहोस् र परीक्षाअघि रातभर नपढ्नुहोस्।" },
      { type: "h2", text: "अन्तिम महिनामा" },
      { type: "ul", items: ["हरेक हप्ता हरेक विषयको एउटा पूर्ण प्रश्नपत्र समय राखेर गर्नुहोस्।", "आफ्नै छोटा नोट्स र सूत्र पानाबाट दोहोर्याउनुहोस्।", "शब्द सीमाभित्र सफासँग उत्तर लेख्ने अभ्यास गर्नुहोस्।"] },
    ],
  },
  {
    slug: "neb-class-12",
    category: "NEB तयारी",
    title: "NEB कक्षा १२: अन्तिम तीन महिनाका लागि व्यावहारिक पुनरावृत्ति योजना",
    excerpt: "NEB बोर्ड परीक्षाअघि नयाँ विषय, पुनरावृत्ति र पूर्ण मक परीक्षाबीच समय कसरी बाँड्ने।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-07-30",
    readMinutes: 7,
    body: [
      { type: "p", text: "सबै कुरा एकैपटक गर्ने प्रयास छोड्नुभयो भने NEB कक्षा १२ को राम्रो तयारीका लागि तीन महिना पर्याप्त हुन्छ। समयलाई तीन स्पष्ट चरणमा बाँड्नुहोस्।" },
      { type: "h2", text: "पहिलो महिना: कमी पूरा गर्नुहोस्" },
      { type: "p", text: "हरेक विषयका सबै अध्यायको सूची बनाउनुहोस् र आत्मविश्वास अनुसार हरियो, पहेँलो वा रातो चिनो लगाउनुहोस्। यो महिना रातोलाई पहेँलोमा बदल्नमा खर्च गर्नुहोस्। रातो अध्यायका पाठ फेरि हेर्नुहोस् र समाधान पढ्नुअघि उदाहरण आफैं हल गर्नुहोस्।" },
      { type: "h2", text: "दोस्रो महिना: समय राखेर अभ्यास" },
      { type: "p", text: "पढ्नेबाट हल गर्नेतर्फ सर्नुहोस्। टाइमर राखेर अध्याय परीक्षा दिनुहोस्। गलत भएका हरेक प्रश्न र त्यसको कारण लेख्नुहोस्: अवधारणाको कमी, हिसाबको गल्ती वा समयको कमजोर प्रयोग। हरेकको उपचार फरक हुन्छ।" },
      { type: "ul", items: ["विज्ञानका विद्यार्थी: भौतिक र रसायन विज्ञानका संख्यात्मक प्रश्न दैनिक गर्नुहोस्।", "व्यवस्थापनका विद्यार्थी: सिद्धान्त मात्र होइन, लेखाका पूर्ण समस्या अभ्यास गर्नुहोस्।", "सबैले: स्पष्ट संरचनासहित लामा उत्तर लेख्ने अभ्यास गर्नुहोस्।"] },
      { type: "h2", text: "तेस्रो महिना: पूर्ण प्रश्नपत्र" },
      { type: "ul", items: ["हरेक हप्ता हरेक विषयको कम्तीमा एउटा पूर्ण मक प्रश्नपत्र गर्नुहोस्।", "गल्ती ताजै हुँदा उही दिन समीक्षा गर्नुहोस्।", "अन्तिम दिनका लागि छोटा सूत्र र मुख्य बुँदाका पाना राख्नुहोस्।", "सबै प्रकारका प्रश्न समेटिए कि भनी जाँच्न NEB नमुना प्रश्न प्रयोग गर्नुहोस्।"] },
      { type: "h2", text: "साना विषयलाई बेवास्ता नगर्नुहोस्" },
      { type: "p", text: "अंग्रेजी र नेपालीको तपाईंको लब्धांकपत्रमा मुख्य विषयकै जति महत्व हुन्छ। अन्तिम समयको हतारोको सट्टा हरेक हप्ता तिनलाई छोटा र नियमित सत्र दिनुहोस्।" },
      { type: "h2", text: "परीक्षाको अघिल्लो रात" },
      { type: "p", text: "नयाँ विषय सुरु नगर्नुहोस्। आफ्ना छोटा नोट्स पढ्नुहोस्, प्रवेशपत्र र सामग्री जाँच्नुहोस्, र समयमै सुत्नुहोस्। शान्त विद्यार्थीले थाकेकाभन्दा बढी सम्झन्छन्।" },
    ],
  },
  {
    slug: "see-to-class-11-science",
    category: "करियर मार्गदर्शन",
    title: "SEE बाट कक्षा ११ विज्ञानमा: के फरक हुन्छ",
    excerpt: "कक्षा ११ विज्ञान ठूलो फड्को जस्तो लाग्छ। के फरक छ र पहिलो त्रैमासिकमा कसरी बानी बसाल्ने, यहाँ छ।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-06-12",
    readMinutes: 5,
    body: [
      { type: "p", text: "धेरैजसो विद्यार्थीलाई कक्षा ११ विज्ञानका पहिला केही हप्ता गाह्रो लाग्छ। यो सामान्य हो। पाठ्यक्रम गहिरो छ, गति छिटो छ, र प्रश्नले कुरा दोहोर्याउन मात्र होइन, प्रयोग गर्न पनि माग्छन्।" },
      { type: "h2", text: "घोक्नुभन्दा अवधारणा" },
      { type: "p", text: "SEE मा प्रायः उत्तर सम्झेर अंक ल्याउन सकिन्थ्यो। कक्षा ११ मा प्रश्नले कुनै कुरा किन काम गर्छ बुझ्नुभयो कि भनी जाँच्छन्। भौतिक र रसायन विज्ञानका पहिला अध्यायमा बढी समय दिनुहोस्, किनभने पछिका अध्याय तिनैमा आधारित हुन्छन्।" },
      { type: "h2", text: "हरेक दिन संख्यात्मक प्रश्न" },
      { type: "p", text: "सप्ताहान्तमा धेरै गर्नुको सट्टा दैनिक केही संख्यात्मक प्रश्न गर्नुहोस्। नियमितताले गति बढाउँछ, र बोर्ड परीक्षामा गति महत्वपूर्ण हुन्छ।" },
      { type: "h2", text: "SEE को गणित दोहोर्याउनुहोस्" },
      { type: "p", text: "कक्षा ९ र १० का बीजगणित, त्रिकोणमिति र आधारभूत ज्यामिति कक्षा ११ को भौतिक र गणितमा जताततै आउँछन्। सुरुमै एक हप्ता तिनलाई दोहोर्याउँदा महिनौंको अलमल बच्छ।" },
      { type: "h2", text: "पहिलो त्रैमासिकमै दिनचर्या बसाल्नुहोस्" },
      { type: "ul", items: ["हरेक दिनको कक्षा २४ घण्टाभित्र दोहोर्याउनुहोस्।", "सूत्र र हल गरिएका उदाहरणका लागि हरेक विषयको छुट्टै कापी राख्नुहोस्।", "जिज्ञासा थुप्रिनुअघि नै सोध्नुहोस्।"] },
      { type: "p", text: "यो फड्को सबैलाई ठूलै लाग्छ। पहिलो त्रैमासिकमा स्थिर बानी बसाल्ने विद्यार्थीलाई बाँकी +2 धेरै सजिलो लाग्छ।" },
    ],
  },
  {
    slug: "specification-grid",
    category: "SEE तयारी",
    title: "विशिष्टीकरण तालिका के हो, र यसलाई कसरी प्रयोग गर्ने?",
    excerpt: "विशिष्टीकरण तालिकाले प्रश्नपत्रमा अंक कसरी बाँडिएको छ देखाउँछ। यसलाई कसरी पढ्ने र अभ्यासको योजना कसरी बनाउने, यहाँ छ।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-05-21",
    readMinutes: 4,
    body: [
      { type: "p", text: "SEE का लागि पाठ्यक्रम विकास केन्द्रले र कक्षा ११ र १२ का लागि NEB ले प्रकाशित गर्ने विशिष्टीकरण तालिकाले प्रश्नपत्रमा अध्याय, प्रश्नको प्रकार र सीपको तह अनुसार अंक कसरी बाँडिएको छ देखाउँछ। यो परीक्षाको नक्साको सबैभन्दा नजिकको कुरा हो।" },
      { type: "h2", text: "यो किन महत्वपूर्ण छ" },
      { type: "p", text: "कुनै अध्यायले धेरै अंक बोक्छ भने त्यसलाई बढी अभ्यास चाहिन्छ। कुनै विषय प्रायः लामो प्रश्नका रूपमा आउँछ भने पढ्ने मात्र होइन, पूर्ण उत्तर लेख्ने अभ्यास पनि गर्नुपर्छ।" },
      { type: "h2", text: "यसलाई कसरी पढ्ने" },
      { type: "ul", items: ["पहिले हरेक अध्याय वा एकाइको अंक हेर्नुहोस्।", "अति छोटा, छोटा र लामा प्रश्नको संख्या जाँच्नुहोस्।", "ज्ञान, बोध, प्रयोग र उच्च दक्षताका प्रश्नको बाँडफाँट ख्याल गर्नुहोस्।"] },
      { type: "h2", text: "यसलाई कसरी प्रयोग गर्ने" },
      { type: "ul", items: ["छापेर वा फोनमा राखेर अध्ययन योजनासँगै राख्नुहोस्।", "पाठ र परीक्षा सकिँदै जाँदा अध्यायमा चिनो लगाउनुहोस्।", "कुन PYQ पहिले गर्ने छान्न यसलाई प्रयोग गर्नुहोस्।"] },
      { type: "p", text: "तपाईंका विषयका विशिष्टीकरण तालिका Note Swift एपभित्रका अध्ययन सामग्रीमा कक्षा अनुसार उपलब्ध छन्।" },
    ],
  },
  {
    slug: "active-recall",
    category: "अध्ययन विधि",
    title: "सक्रिय स्मरण: दोहोर्याएर पढ्नुभन्दा राम्रो अध्ययन बानी",
    excerpt: "फेरि पढ्दा काम गरेजस्तो लाग्छ। आफैंलाई जाँच्दा साँच्चै काम हुन्छ। सक्रिय स्मरणबाट पढ्ने छोटो गाइड।",
    author: "Note Swift शैक्षिक टिम",
    date: "2026-04-09",
    readMinutes: 4,
    body: [
      { type: "p", text: "सक्रिय स्मरण भनेको किताब बन्द गरेर भर्खरै सिकेको कुरा सम्झने प्रयास गर्नु हो। यो फेरि पढ्नुभन्दा गाह्रो छ, र त्यसैले काम गर्छ। हरेक पटक दिमागबाट कुनै कुरा निकाल्दा अर्को पटक त्यो भेट्टाउन सजिलो हुन्छ।" },
      { type: "h2", text: "फेरि पढ्नुले किन भ्रम दिन्छ" },
      { type: "p", text: "पृष्ठ फेरि पढ्दा त्यो परिचित लाग्छ, र परिचित हुनु जानेजस्तो लाग्छ। तर उत्तर चिन्नु, परीक्षा हलमा उत्तर लेख्नुभन्दा धेरै सजिलो हुन्छ।" },
      { type: "h2", text: "आजै प्रयास गर्ने तीन तरिका" },
      { type: "ul", items: ["हरेक पाठपछि सम्झेर तीनवटा मुख्य बुँदा लेख्नुहोस्।", "अध्याय पढेलगत्तै MCQ र छोटा प्रश्न गर्नुहोस्।", "साथीलाई सिकाएझैं अवधारणा ठूलो स्वरमा बुझाउनुहोस्।"] },
      { type: "h2", text: "अन्तरालसँग जोड्नुहोस्" },
      { type: "p", text: "केही समयपछि विषयमा फर्किँदा स्मरण सबैभन्दा राम्रो काम गर्छ: भोलिपल्ट, एक हप्तापछि, अनि एक महिनापछि। छोटा र अन्तरालयुक्त सत्रले एउटा लामो सत्रलाई जित्छन्।" },
      { type: "p", text: "Note Swift एपको Test ट्याबका अध्याय परीक्षा र दैनिक अभ्यास ठ्याक्कै यही बानीका लागि बनाइएका हुन्।" },
    ],
  },
];

export const posts: Record<Locale, Post[]> = { en, ne };

export const blogCopy = {
  en: {
    meta: { title: "Blog: Study tips, SEE and NEB guides", description: "Study tips, SEE and NEB preparation guides, and education insights for students in Nepal from the Note Swift academic team." },
    crumb: "Blog",
    title: "Study smarter. Read this first.",
    lead: "Guides, study tips and exam advice from the Note Swift academic team.",
    all: "All",
    filterLabel: "Filter posts by category",
    empty: "No posts in this category yet. Check back soon.",
    featured: "Latest",
    minRead: "min read",
    by: "By",
    published: "Published",
    keepReading: "Keep reading",
    ctaTitle: "Put this into practice.",
    ctaLead: "Lessons, notes and tests for your class, in the Note Swift app.",
    back: "All posts",
  },
  ne: {
    meta: { title: "ब्लग: अध्ययन सुझाव, SEE र NEB गाइड", description: "Note Swift शैक्षिक टिमबाट नेपालका विद्यार्थीका लागि अध्ययन सुझाव, SEE र NEB तयारी गाइड र शैक्षिक जानकारी।" },
    crumb: "ब्लग",
    title: "स्मार्ट तरिकाले पढ्नुहोस्। पहिले यो पढ्नुहोस्।",
    lead: "Note Swift शैक्षिक टिमका गाइड, अध्ययन सुझाव र परीक्षा सल्लाह।",
    all: "सबै",
    filterLabel: "श्रेणी अनुसार लेख छान्नुहोस्",
    empty: "यो श्रेणीमा अहिलेसम्म कुनै लेख छैन। छिट्टै फेरि हेर्नुहोस्।",
    featured: "नयाँ",
    minRead: "मिनेट पढाइ",
    by: "लेखक",
    published: "प्रकाशित",
    keepReading: "थप पढ्नुहोस्",
    ctaTitle: "यसलाई अभ्यासमा उतार्नुहोस्।",
    ctaLead: "तपाईंको कक्षाका पाठ, नोट्स र परीक्षा, Note Swift एपमा।",
    back: "सबै लेख",
  },
} satisfies Record<Locale, unknown>;

export const formatDate = (iso: string, lang: Locale) =>
  new Date(iso + "T00:00:00Z").toLocaleDateString(lang === "ne" ? "ne-NP" : "en-GB", { day: "numeric", month: "long", year: "numeric", timeZone: "UTC" });

/** Card shape used by PostCard / BlogFilter. */
export const toCard = (p: Post, lang: Locale) => ({
  href: localePath(lang, `/blog/${p.slug}`),
  category: p.category,
  title: p.title,
  excerpt: p.excerpt,
  date: formatDate(p.date, lang),
  read: `${p.readMinutes} ${blogCopy[lang].minRead}`,
});

/** Newest first. */
export const sortedPosts = (lang: Locale) => [...posts[lang]].sort((a, b) => b.date.localeCompare(a.date));
