import type { Locale } from "@/lib/i18n";
import { site } from "@/lib/site";

export type HelpItem = { cat: string; q: string; a: string };

const en = {
  meta: {
    title: "Help center",
    description: "Answers about Note Swift: getting started, courses, payments and enrolment, technical support, and information for parents and schools.",
  },
  crumb: "Help center",
  hero: { title: "How can we help?", lead: "Search the answers below or pick a topic. If you do not find what you need, write to us." },
  search: { label: "Search help", placeholder: "Search, for example: enrol, payment, Play Store", clear: "Clear search" },
  filterLabel: "Filter by topic",
  all: "All topics",
  results: "{n} answers",
  empty: { title: "No answers match your search.", body: "Try a shorter word, or choose another topic. You can also contact us directly below.", reset: "Show all answers" },
  categories: ["Getting started", "Courses", "Payments and enrolment", "Technical support", "Parents", "Schools"],
  items: [
    { cat: "Getting started", q: "What is Note Swift?", a: "Note Swift is a learning platform for students in Nepal. The student app has video lessons, notes, practice, tests and SikAI, an AI assistant, for SEE, Class 11 and Class 12 under the CDC and NEB syllabus." },
    { cat: "Getting started", q: "How do I start learning?", a: `Open the student app at ${site.appUrl} in your browser, or install the Android app from Google Play. Create your account, choose your class, and pick a course to start.` },
    { cat: "Getting started", q: "Which classes does Note Swift cover?", a: "SEE (Class 10), Class 11 and Class 12. Class 10 follows the CDC syllabus. Class 11 and 12 follow the NEB curriculum, with Science and Management courses." },
    { cat: "Getting started", q: "Is there an app for my phone?", a: `Yes. The Android app is on Google Play (${site.playStore}). You can also use the student app in any browser at ${site.appUrl}.` },
    { cat: "Courses", q: "What is included in a course?", a: "A course has lessons organised by subject and chapter, notes, practice questions, MCQs and chapter tests. Pro courses also unlock SikAI in the Ask tab." },
    { cat: "Courses", q: "Can I study in Nepali medium?", a: "Yes. SEE is available in both English medium and Nepali medium, aligned with the CDC textbook." },
    { cat: "Courses", q: "What is SikAI?", a: "SikAI is the AI learning assistant inside the app. You choose a subject and a module, ask your question, and it explains in the context of that course. It is a study aid, not a replacement for lessons or teachers." },
    { cat: "Courses", q: "Does SikAI solve a question from a photo?", a: "No. SikAI works through chat by subject and module. A question generator for SikAI is coming soon." },
    { cat: "Courses", q: "Where do I find chapter tests and past questions?", a: "Open the Test tab in the student app for chapter tests, MCQs and your results. Notes, important questions and past year questions are in the study materials of your course." },
    { cat: "Payments and enrolment", q: "How do I enrol in a course?", a: `Enrolment happens inside the student app at ${site.appUrl}. Choose the course, review the details and complete enrolment there.` },
    { cat: "Payments and enrolment", q: "How do I pay for a course?", a: "You pay in the student app when you enrol. The payment options available to you are shown at checkout. The website does not take payments." },
    { cat: "Payments and enrolment", q: "I paid but my course is not unlocked. What should I do?", a: `Close and reopen the app, then check your enrolled courses. If the course is still locked, email ${site.email.support} with your registered email or phone number and the time of payment, or message us on WhatsApp.` },
    { cat: "Payments and enrolment", q: "Can I ask for a refund?", a: `Write to ${site.email.support} with your account details and the reason. Our team will review the request and reply by email.` },
    { cat: "Technical support", q: "I cannot log in. What can I do?", a: "Check that you are using the email or phone number you registered with, then use the password reset option on the sign in screen. If it still fails, contact support and tell us what message you see." },
    { cat: "Technical support", q: "Videos are not playing or keep buffering.", a: "Check your internet connection and try again, or switch between Wi-Fi and mobile data. Update the app to the latest version from Google Play and restart it. If the problem stays, send us the course and lesson name." },
    { cat: "Technical support", q: "How do I update the app?", a: "Open Google Play, search for Note Swift and tap Update if it is available. You can also use the student app in a browser, which is always the latest version." },
    { cat: "Technical support", q: "How do I report a problem?", a: `Email ${site.email.support}, message us on WhatsApp, or call ${site.phone}. Tell us your class, your phone model and what happened, and add a screenshot if you can.` },
    { cat: "Parents", q: "How can I follow my child's progress?", a: `Parents have their own portal at ${site.portals.parent}. It shows learning activity and results linked to your child's account.` },
    { cat: "Parents", q: "Is Note Swift safe for children?", a: "SikAI is meant for study questions inside a course, and our Terms of Use do not allow misuse. For questions about privacy or your child's account, contact support." },
    { cat: "Parents", q: "Do I need to buy the course for my child?", a: "Your child can enrol and pay in the student app, or you can do it for them using their account. Contact us if you need help with either." },
    { cat: "Schools", q: "How can my school use Note Swift?", a: `Schools get tools for leaders and teachers through the school portal at ${site.portals.school}. To start a partnership, contact us at ${site.email.contact}.` },
    { cat: "Schools", q: "Do teachers have a separate portal?", a: `Yes. Teachers use ${site.portals.teacher} to manage their classes and content.` },
    { cat: "Schools", q: "Where can I read about school partnerships?", a: "See the For schools and School partnership pages on this website, or write to us and our team will respond." },
  ] as HelpItem[],
  contact: {
    title: "Still need help?",
    lead: "Write to the support team. Include your class and phone model if it is about the app.",
    email: "Email support",
    whatsapp: "WhatsApp",
    phone: "Call us",
  },
};

const ne: typeof en = {
  meta: {
    title: "सहायता केन्द्र",
    description: "Note Swift बारे जवाफ: सुरु गर्ने तरिका, कोर्स, भुक्तानी र भर्ना, प्राविधिक सहायता, अभिभावक र विद्यालयसम्बन्धी जानकारी।",
  },
  crumb: "सहायता केन्द्र",
  hero: { title: "हामी कसरी मद्दत गर्न सक्छौं?", lead: "तलका जवाफ खोज्नुहोस् वा विषय छान्नुहोस्। चाहिएको कुरा भेटिएन भने हामीलाई लेख्नुहोस्।" },
  search: { label: "सहायता खोज्नुहोस्", placeholder: "खोज्नुहोस्, जस्तै: भर्ना, भुक्तानी, Play Store", clear: "खोजी हटाउनुहोस्" },
  filterLabel: "विषय अनुसार छान्नुहोस्",
  all: "सबै विषय",
  results: "{n} जवाफ",
  empty: { title: "तपाईंको खोजीसँग मिल्ने जवाफ भेटिएन।", body: "छोटो शब्द प्रयोग गर्नुहोस् वा अर्को विषय छान्नुहोस्। तल सिधै सम्पर्क पनि गर्न सक्नुहुन्छ।", reset: "सबै जवाफ देखाउनुहोस्" },
  categories: ["सुरु गर्ने तरिका", "कोर्स", "भुक्तानी र भर्ना", "प्राविधिक सहायता", "अभिभावक", "विद्यालय"],
  items: [
    { cat: "सुरु गर्ने तरिका", q: "Note Swift भनेको के हो?", a: "Note Swift नेपालका विद्यार्थीका लागि सिकाइ प्लेटफर्म हो। विद्यार्थी एपमा CDC र NEB पाठ्यक्रम अनुसार SEE, कक्षा ११ र कक्षा १२ का भिडियो पाठ, नोट्स, अभ्यास, परीक्षा र AI सहायक SikAI छन्।" },
    { cat: "सुरु गर्ने तरिका", q: "सिक्न कसरी सुरु गर्ने?", a: `ब्राउजरमा ${site.appUrl} मा विद्यार्थी एप खोल्नुहोस्, वा Google Play बाट एन्ड्रोइड एप इन्स्टल गर्नुहोस्। खाता बनाउनुहोस्, आफ्नो कक्षा छान्नुहोस् र कोर्स रोज्नुहोस्।` },
    { cat: "सुरु गर्ने तरिका", q: "Note Swift ले कुन कक्षा समेट्छ?", a: "SEE (कक्षा १०), कक्षा ११ र कक्षा १२। कक्षा १० CDC पाठ्यक्रम अनुसार छ। कक्षा ११ र १२ NEB पाठ्यक्रम अनुसार छन्, जसमा विज्ञान र व्यवस्थापन कोर्स छन्।" },
    { cat: "सुरु गर्ने तरिका", q: "फोनका लागि एप छ?", a: `छ। एन्ड्रोइड एप Google Play (${site.playStore}) मा छ। ${site.appUrl} मा कुनै पनि ब्राउजरबाट विद्यार्थी एप चलाउन पनि सकिन्छ।` },
    { cat: "कोर्स", q: "कोर्समा के के समावेश हुन्छ?", a: "कोर्समा विषय र अध्याय अनुसार मिलाइएका पाठ, नोट्स, अभ्यास प्रश्न, MCQ र अध्याय परीक्षा हुन्छन्। Pro कोर्सले Ask ट्याबमा SikAI पनि खोल्छ।" },
    { cat: "कोर्स", q: "के नेपाली माध्यममा पढ्न सकिन्छ?", a: "सकिन्छ। SEE अंग्रेजी माध्यम र नेपाली माध्यम दुवैमा उपलब्ध छ, जुन CDC पाठ्यपुस्तकसँग मिल्छ।" },
    { cat: "कोर्स", q: "SikAI भनेको के हो?", a: "SikAI एपभित्रको AI सिकाइ सहायक हो। तपाईं विषय र मोड्युल छान्नुहुन्छ, प्रश्न सोध्नुहुन्छ, र त्यो कोर्सको सन्दर्भमा व्याख्या पाउनुहुन्छ। यो अध्ययनको सहयोगी हो, पाठ वा शिक्षकको विकल्प होइन।" },
    { cat: "कोर्स", q: "के SikAI ले फोटोबाट प्रश्न हल गर्छ?", a: "गर्दैन। SikAI विषय र मोड्युल अनुसार च्याटमार्फत काम गर्छ। SikAI का लागि प्रश्न निर्माता छिट्टै आउँदैछ।" },
    { cat: "कोर्स", q: "अध्याय परीक्षा र पुराना प्रश्न कहाँ पाइन्छ?", a: "अध्याय परीक्षा, MCQ र नतिजाका लागि विद्यार्थी एपको Test ट्याब खोल्नुहोस्। नोट्स, महत्त्वपूर्ण प्रश्न र पुराना वर्षका प्रश्न तपाईंको कोर्सको अध्ययन सामग्रीमा छन्।" },
    { cat: "भुक्तानी र भर्ना", q: "कोर्समा भर्ना कसरी हुने?", a: `भर्ना ${site.appUrl} को विद्यार्थी एपभित्र हुन्छ। कोर्स छान्नुहोस्, विवरण हेर्नुहोस् र त्यहीँ भर्ना पूरा गर्नुहोस्।` },
    { cat: "भुक्तानी र भर्ना", q: "कोर्सको भुक्तानी कसरी गर्ने?", a: "भर्ना गर्दा विद्यार्थी एपमै भुक्तानी गर्नुहुन्छ। तपाईंलाई उपलब्ध भुक्तानी विकल्प चेकआउटमा देखिन्छन्। वेबसाइटले भुक्तानी लिँदैन।" },
    { cat: "भुक्तानी र भर्ना", q: "भुक्तानी गरेँ तर कोर्स खुलेन, के गर्ने?", a: `एप बन्द गरेर फेरि खोल्नुहोस् र भर्ना भएका कोर्स हेर्नुहोस्। कोर्स अझै बन्द भए, दर्ता गरेको इमेल वा फोन नम्बर र भुक्तानी गरेको समयसहित ${site.email.support} मा इमेल गर्नुहोस्, वा WhatsApp मा सन्देश पठाउनुहोस्।` },
    { cat: "भुक्तानी र भर्ना", q: "के रकम फिर्ता माग्न सकिन्छ?", a: `खाताको विवरण र कारणसहित ${site.email.support} मा लेख्नुहोस्। हाम्रो टोलीले अनुरोध हेरेर इमेलमै जवाफ दिनेछ।` },
    { cat: "प्राविधिक सहायता", q: "लग इन गर्न सकिरहेको छैन, के गर्ने?", a: "दर्ता गर्दा प्रयोग गरेकै इमेल वा फोन नम्बर प्रयोग गरिरहेको जाँच गर्नुहोस्, अनि साइन इन स्क्रिनको पासवर्ड रिसेट विकल्प प्रयोग गर्नुहोस्। फेरि नभए सहायतामा सम्पर्क गरी कस्तो सन्देश देखिन्छ बताउनुहोस्।" },
    { cat: "प्राविधिक सहायता", q: "भिडियो चल्दैन वा बारम्बार रोकिन्छ।", a: "इन्टरनेट जडान जाँचेर फेरि प्रयास गर्नुहोस्, वा Wi-Fi र मोबाइल डेटा बदल्नुहोस्। Google Play बाट एप नयाँ संस्करणमा अपडेट गरी फेरि खोल्नुहोस्। समस्या रहिरह्यो भने कोर्स र पाठको नाम पठाउनुहोस्।" },
    { cat: "प्राविधिक सहायता", q: "एप कसरी अपडेट गर्ने?", a: "Google Play खोल्नुहोस्, Note Swift खोज्नुहोस् र Update देखिए त्यसमा थिच्नुहोस्। ब्राउजरमा विद्यार्थी एप पनि चलाउन सकिन्छ, जुन सधैं नयाँ संस्करण हुन्छ।" },
    { cat: "प्राविधिक सहायता", q: "समस्या कसरी रिपोर्ट गर्ने?", a: `${site.email.support} मा इमेल गर्नुहोस्, WhatsApp मा सन्देश पठाउनुहोस्, वा ${site.phone} मा फोन गर्नुहोस्। आफ्नो कक्षा, फोनको मोडल र के भयो बताउनुहोस्, सकेसम्म स्क्रिनसट पनि पठाउनुहोस्।` },
    { cat: "अभिभावक", q: "छोराछोरीको प्रगति कसरी हेर्ने?", a: `अभिभावकका लागि ${site.portals.parent} मा आफ्नै पोर्टल छ। त्यहाँ तपाईंको बच्चाको खातासँग जोडिएको सिकाइ गतिविधि र नतिजा देखिन्छ।` },
    { cat: "अभिभावक", q: "के Note Swift बालबालिकाका लागि सुरक्षित छ?", a: "SikAI कोर्सभित्रका अध्ययन प्रश्नका लागि हो, र हाम्रो प्रयोगका सर्तले दुरुपयोगको अनुमति दिँदैन। गोपनीयता वा बच्चाको खातासम्बन्धी प्रश्न भए सहायतामा सम्पर्क गर्नुहोस्।" },
    { cat: "अभिभावक", q: "के मैले बच्चाका लागि कोर्स किन्नुपर्छ?", a: "तपाईंको बच्चाले विद्यार्थी एपमा भर्ना र भुक्तानी गर्न सक्छ, वा तपाईंले उसको खाता प्रयोग गरी गरिदिन सक्नुहुन्छ। दुवैमा सहयोग चाहिए हामीलाई सम्पर्क गर्नुहोस्।" },
    { cat: "विद्यालय", q: "हाम्रो विद्यालयले Note Swift कसरी प्रयोग गर्न सक्छ?", a: `विद्यालयले ${site.portals.school} को विद्यालय पोर्टलमार्फत नेतृत्व र शिक्षकका लागि उपकरण पाउँछ। साझेदारी सुरु गर्न ${site.email.contact} मा सम्पर्क गर्नुहोस्।` },
    { cat: "विद्यालय", q: "शिक्षकका लागि छुट्टै पोर्टल छ?", a: `छ। शिक्षकहरूले आफ्ना कक्षा र सामग्री व्यवस्थापन गर्न ${site.portals.teacher} प्रयोग गर्छन्।` },
    { cat: "विद्यालय", q: "विद्यालय साझेदारीबारे कहाँ पढ्न सकिन्छ?", a: "यो वेबसाइटका विद्यालयका लागि र विद्यालय साझेदारी पृष्ठ हेर्नुहोस्, वा हामीलाई लेख्नुहोस्। हाम्रो टोलीले जवाफ दिनेछ।" },
  ],
  contact: {
    title: "अझै मद्दत चाहियो?",
    lead: "सहायता टोलीलाई लेख्नुहोस्। एपसम्बन्धी भए आफ्नो कक्षा र फोनको मोडल पनि उल्लेख गर्नुहोस्।",
    email: "इमेल सहायता",
    whatsapp: "WhatsApp",
    phone: "फोन गर्नुहोस्",
  },
};

export const help: Record<Locale, typeof en> = { en, ne };
