const en = {
  meta: {
    title: "Note Swift | Learning platform for SEE, Class 11 and Class 12 in Nepal",
    description: "Video lessons, notes, practice tests, live classes and SikAI, the AI learning assistant. Mapped to the NEB and CDC syllabus for students in Nepal.",
  },
  hero: {
    eyebrow: "For SEE, Class 11 and Class 12",
    title: "The smarter way to learn.",
    lead: "Lessons, notes, tests, live classes and SikAI in one app, mapped to your NEB and CDC syllabus.",
    phoneHome: "Note Swift student app home screen with today's live class and quick access tools",
    phoneChat: "SikAI chat explaining an electrostatics question step by step",
    chipLive: "Live class",
    chipLiveSub: "Rotational Dynamics",
    chipSyllabus: "Mapped to NEB and CDC",
  },
  proof: ["NEB curriculum", "CDC syllabus", "Nepali and English medium", "Android app on Google Play"],
  ecosystem: {
    eyebrow: "The ecosystem",
    title: "One ecosystem. Built around learning.",
    lead: "Note Swift is more than a course or a video library. It connects everyone and everything a student's learning depends on.",
    center: "Note Swift",
    select: "Show",
    nodes: [
      { key: "students", label: "Students", body: "Lessons, notes, tests and SikAI in one app, chapter by chapter.", link: "Open student app" },
      { key: "parents", label: "Parents", body: "Attendance, results and progress, visible without guessing.", link: "Parent portal" },
      { key: "schools", label: "Schools", body: "Digital tools that support the classroom, not replace it.", link: "School portal" },
      { key: "teachers", label: "Teachers", body: "Run live classes, share resources and check work faster.", link: "Teacher portal" },
      { key: "content", label: "Content", body: "Video lessons and notes mapped to the NEB and CDC syllabus.", link: "Browse courses" },
      { key: "technology", label: "Technology", body: "One shared platform, so every app works from the same data.", link: "See all features" },
    ],
  },
  stats: {
    title: "Growing every day.",
    sub: "Built one lesson, one student, one school at a time.",
    items: { videos: "Learning videos", resources: "Learning resources", students: "Students reached", schools: "Schools and communities" },
  },
  features: {
    title: "Everything a chapter needs, in one place.",
    lead: "Six tools that work together, from the first lesson to the final exam.",
    items: [
      { key: "home", title: "Your day, organised", body: "Today's live classes, your batches, downloads and doubts, one tap away from the home screen." },
      { key: "learn", title: "Every subject, chapter by chapter", body: "Subjects follow your syllabus, with lessons, notes and saved material inside each one." },
      { key: "lesson", title: "Video lessons that get to the point", body: "Clear lessons from experienced teachers. Pause, replay, download and ask about any moment." },
      { key: "test", title: "Practice like the real exam", body: "MCQ and subjective tests with scores, timers and scheduled papers from your teachers." },
      { key: "chat", title: "Ask SikAI when you are stuck", body: "Pick a subject and module, then ask. SikAI explains the steps instead of handing you an answer." },
      { key: "progress", title: "Know exactly where you stand", body: "Tests, assignments and attendance for every subject, so you know what to revise next." },
    ],
  },
  sikai: {
    eyebrow: "SikAI",
    title: "An AI learning assistant that explains.",
    lead: "SikAI works inside your course. Choose the subject and module, and it answers in the context of what you are studying.",
    points: [
      { title: "Follows your syllabus", body: "Questions stay tied to your course, subject and module." },
      { title: "Explains the method", body: "Step-by-step answers, so you can solve the next one yourself." },
      { title: "Available any time", body: "Late night or early morning, ask as many times as you need." },
      { title: "Question generator", body: "Fresh practice questions for any chapter. Coming soon." },
    ],
    link: "Meet SikAI",
    phone: "SikAI welcome screen inviting the student to start a new chat",
  },
  nepal: {
    title: "Made for the way Nepal learns.",
    lead: "Our syllabus, our exams, our teachers. Built for students from Mahendranagar to Biratnagar, on the phone they already have.",
    points: [
      { title: "NEB curriculum", body: "Class 11 and 12 content follows the NEB structure." },
      { title: "CDC syllabus", body: "SEE lessons map to the CDC syllabus, chapter by chapter." },
      { title: "Local teachers", body: "Taught by teachers who know Nepali classrooms and exams." },
      { title: "Your medium", body: "Class 10 is available in both Nepali and English medium." },
    ],
    map: "Map of Nepal marking cities where students learn with Note Swift",
  },
  steps: {
    title: "From first lesson to final exam.",
    items: [
      { title: "Choose your class", body: "Pick Class 10, 11 or 12 and your stream or medium." },
      { title: "Learn the chapter", body: "Watch the lesson, then read the notes beside it." },
      { title: "Practise daily", body: "Short MCQ sets help you remember what you learned." },
      { title: "Test yourself", body: "Chapter tests and mock exams show where you stand." },
      { title: "Fix weak topics", body: "Your results point to what to revise. Ask SikAI." },
    ],
  },
  courses: {
    title: "Find your class.",
    lead: "Courses organised by class, stream and medium.",
    all: "See all courses",
    view: "Explore {class}",
    tabs: { overview: "Overview", curriculum: "Curriculum" },
    included: "Included in every course",
    features: ["Recorded video lessons", "Live classes", "Chapter-wise notes", "Chapter MCQs and tests", "Model sets with solutions", "Ask SikAI any time"],
    totals: { subjects: "Subjects", chapters: "Chapters", videos: "Video lessons", notes: "Notes" },
  },
  schools: {
    title: "Bring Note Swift to your school.",
    lead: "Attendance, assignments, tests and reports for leaders and teachers, with the student app for every learner.",
    secondary: "How partnership works",
    features: ["Attendance", "Assignments", "Online tests", "Reports"],
  },
  // TODO: placeholder quotes. Replace with real, consented student testimonials before launch.
  stories: {
    eyebrow: "Student stories",
    title: "In their own words.",
    prev: "Previous story",
    next: "Next story",
    items: [
      { quote: "I used to watch random videos and still feel lost. Having lessons, notes and questions for each chapter in one place made my revision a lot calmer.", name: "Aayusha Shrestha", role: "Class 12 Science, Kathmandu" },
      { quote: "SikAI explains the steps instead of giving me the answer. Now I can solve the next physics numerical on my own.", name: "Bibek Thapa", role: "Class 11 Science, Pokhara" },
      { quote: "The chapter tests feel like the real SEE paper. I finally knew which topics to revise before the exam.", name: "Sarita Chaudhary", role: "Class 10, Dhangadhi" },
      { quote: "I download lessons at school and watch them at home where the internet is slow. That alone changed how much I study.", name: "Rojan Magar", role: "Class 10, Gorkha" },
      { quote: "Accounts finally makes sense. The teacher goes slowly and the notes match exactly what we study in class.", name: "Prasansa Karki", role: "Class 12 Management, Biratnagar" },
      { quote: "Live classes in the evening fit around my tuition. If I miss one, the recording is there the next morning.", name: "Nischal Adhikari", role: "Class 11 Science, Butwal" },
    ],
  },
  final: {
    title: "Start with one chapter.",
    lead: "See how much easier it gets.",
  },
};

export type HomeCopy = typeof en;

const ne: HomeCopy = {
  meta: {
    title: "Note Swift | नेपालमा SEE, कक्षा ११ र कक्षा १२ का लागि सिकाइ प्लेटफर्म",
    description: "भिडियो पाठ, नोट्स, अभ्यास परीक्षा, लाइभ कक्षा र AI सिकाइ सहायक SikAI। नेपालका विद्यार्थीका लागि NEB र CDC पाठ्यक्रम अनुसार।",
  },
  hero: {
    eyebrow: "SEE, कक्षा ११ र कक्षा १२ का लागि",
    title: "सिक्ने अझ स्मार्ट तरिका।",
    lead: "पाठ, नोट्स, परीक्षा, लाइभ कक्षा र SikAI, सबै एउटै एपमा, तपाईंको NEB र CDC पाठ्यक्रम अनुसार।",
    phoneHome: "आजको लाइभ कक्षा र छिटो पहुँच उपकरणसहित Note Swift विद्यार्थी एपको होम स्क्रिन",
    phoneChat: "इलेक्ट्रोस्टेटिक्सको प्रश्न चरणबद्ध रूपमा बुझाउँदै SikAI च्याट",
    chipLive: "लाइभ कक्षा",
    chipLiveSub: "Rotational Dynamics",
    chipSyllabus: "NEB र CDC अनुसार",
  },
  proof: ["NEB पाठ्यक्रम", "CDC पाठ्यक्रम", "नेपाली र अंग्रेजी माध्यम", "Google Play मा एन्ड्रोइड एप"],
  ecosystem: {
    eyebrow: "इकोसिस्टम",
    title: "एउटै इकोसिस्टम। सिकाइको वरिपरि बनेको।",
    lead: "Note Swift केवल कोर्स वा भिडियो लाइब्रेरी होइन। यसले विद्यार्थीको सिकाइ निर्भर हुने सबैलाई र सबै कुरालाई जोड्छ।",
    center: "Note Swift",
    select: "हेर्नुहोस्",
    nodes: [
      { key: "students", label: "विद्यार्थी", body: "पाठ, नोट्स, परीक्षा र SikAI एउटै एपमा, अध्याय अनुसार।", link: "विद्यार्थी एप खोल्नुहोस्" },
      { key: "parents", label: "अभिभावक", body: "हाजिरी, नतिजा र प्रगति अनुमान नगरी हेर्नुहोस्।", link: "अभिभावक पोर्टल" },
      { key: "schools", label: "विद्यालय", body: "कक्षाकोठालाई सहयोग गर्ने डिजिटल उपकरण, विस्थापन गर्ने होइन।", link: "विद्यालय पोर्टल" },
      { key: "teachers", label: "शिक्षक", body: "लाइभ कक्षा चलाउनुहोस्, सामग्री बाँड्नुहोस् र काम छिटो जाँच्नुहोस्।", link: "शिक्षक पोर्टल" },
      { key: "content", label: "सामग्री", body: "NEB र CDC पाठ्यक्रम अनुसारका भिडियो पाठ र नोट्स।", link: "कोर्सहरू हेर्नुहोस्" },
      { key: "technology", label: "प्रविधि", body: "एउटै साझा प्लेटफर्म, त्यसैले हरेक एप एउटै डाटाबाट चल्छ।", link: "सबै सुविधा हेर्नुहोस्" },
    ],
  },
  stats: {
    title: "हरेक दिन बढ्दै।",
    sub: "एक पाठ, एक विद्यार्थी, एक विद्यालय गर्दै बनेको।",
    items: { videos: "सिकाइ भिडियो", resources: "सिकाइ सामग्री", students: "विद्यार्थीसम्म पुगेको", schools: "विद्यालय र समुदाय" },
  },
  features: {
    title: "एउटा अध्यायलाई चाहिने सबै कुरा, एकै ठाउँमा।",
    lead: "पहिलो पाठदेखि अन्तिम परीक्षासम्म सँगै काम गर्ने छवटा उपकरण।",
    items: [
      { key: "home", title: "तपाईंको दिन, व्यवस्थित", body: "आजका लाइभ कक्षा, ब्याच, डाउनलोड र जिज्ञासा, होम स्क्रिनबाट एक ट्यापमै।" },
      { key: "learn", title: "हरेक विषय, अध्याय अनुसार", body: "विषयहरू तपाईंको पाठ्यक्रम अनुसार छन्, हरेकभित्र पाठ, नोट्स र सुरक्षित सामग्री।" },
      { key: "lesson", title: "सिधै बुझिने भिडियो पाठ", body: "अनुभवी शिक्षकका स्पष्ट पाठ। रोक्नुहोस्, फेरि हेर्नुहोस्, डाउनलोड गर्नुहोस् र जुनसुकै भागबारे सोध्नुहोस्।" },
      { key: "test", title: "वास्तविक परीक्षाजस्तै अभ्यास", body: "अंक, टाइमर र शिक्षकले तय गरेका प्रश्नपत्रसहित MCQ र विषयगत परीक्षा।" },
      { key: "chat", title: "अड्किँदा SikAI लाई सोध्नुहोस्", body: "विषय र मोड्युल छान्नुहोस् अनि सोध्नुहोस्। SikAI ले सिधै उत्तर दिनुको सट्टा चरणहरू बुझाउँछ।" },
      { key: "progress", title: "आफू कहाँ छु, ठ्याक्कै थाहा पाउनुहोस्", body: "हरेक विषयको परीक्षा, असाइनमेन्ट र हाजिरी, ताकि अब के दोहोर्याउने थाहा होस्।" },
    ],
  },
  sikai: {
    eyebrow: "SikAI",
    title: "बुझाएर सिकाउने AI सिकाइ सहायक।",
    lead: "SikAI तपाईंको कोर्सभित्रै काम गर्छ। विषय र मोड्युल छान्नुहोस्, अनि यसले तपाईंले पढिरहेको सन्दर्भमा उत्तर दिन्छ।",
    points: [
      { title: "तपाईंको पाठ्यक्रम पछ्याउँछ", body: "प्रश्नहरू तपाईंको कोर्स, विषय र मोड्युलसँग जोडिएका हुन्छन्।" },
      { title: "विधि बुझाउँछ", body: "चरणबद्ध उत्तर, ताकि अर्को प्रश्न आफैं हल गर्न सक्नुहोस्।" },
      { title: "जुनसुकै बेला उपलब्ध", body: "राति अबेर होस् वा बिहान सबेरै, जति पटक चाहिन्छ सोध्नुहोस्।" },
      { title: "प्रश्न जेनेरेटर", body: "जुनसुकै अध्यायका लागि नयाँ अभ्यास प्रश्न। छिट्टै आउँदैछ।" },
    ],
    link: "SikAI बारे जान्नुहोस्",
    phone: "विद्यार्थीलाई नयाँ च्याट सुरु गर्न आमन्त्रण गर्दै SikAI को स्वागत स्क्रिन",
  },
  nepal: {
    title: "नेपालको सिकाइ शैलीका लागि बनेको।",
    lead: "हाम्रो पाठ्यक्रम, हाम्रा परीक्षा, हाम्रा शिक्षक। महेन्द्रनगरदेखि विराटनगरसम्मका विद्यार्थीका लागि, उनीहरूसँग भएकै फोनमा।",
    points: [
      { title: "NEB पाठ्यक्रम", body: "कक्षा ११ र १२ का सामग्री NEB संरचना अनुसार छन्।" },
      { title: "CDC पाठ्यक्रम", body: "SEE का पाठहरू CDC पाठ्यक्रमसँग अध्याय अनुसार मिल्छन्।" },
      { title: "स्थानीय शिक्षक", body: "नेपाली कक्षाकोठा र परीक्षा बुझेका शिक्षकले पढाउँछन्।" },
      { title: "तपाईंकै माध्यम", body: "कक्षा १० नेपाली र अंग्रेजी दुवै माध्यममा उपलब्ध छ।" },
    ],
    map: "Note Swift सँग विद्यार्थीहरू सिकिरहेका सहरहरू देखाउने नेपालको नक्सा",
  },
  steps: {
    title: "पहिलो पाठदेखि अन्तिम परीक्षासम्म।",
    items: [
      { title: "कक्षा छान्नुहोस्", body: "कक्षा १०, ११ वा १२ र आफ्नो संकाय वा माध्यम छान्नुहोस्।" },
      { title: "अध्याय सिक्नुहोस्", body: "पाठ हेर्नुहोस्, अनि सँगैको नोट्स पढ्नुहोस्।" },
      { title: "दैनिक अभ्यास", body: "छोटा MCQ सेटले सिकेको कुरा सम्झन मद्दत गर्छ।" },
      { title: "आफैंलाई जाँच्नुहोस्", body: "अध्याय परीक्षा र मक परीक्षाले तपाईं कहाँ हुनुहुन्छ देखाउँछ।" },
      { title: "कमजोर विषय सुधार्नुहोस्", body: "नतिजाले के दोहोर्याउने देखाउँछ। SikAI लाई सोध्नुहोस्।" },
    ],
  },
  courses: {
    title: "आफ्नो कक्षा खोज्नुहोस्।",
    lead: "कक्षा, संकाय र माध्यम अनुसार व्यवस्थित कोर्सहरू।",
    all: "सबै कोर्स हेर्नुहोस्",
    view: "{class} हेर्नुहोस्",
    tabs: { overview: "सारांश", curriculum: "पाठ्यक्रम" },
    included: "हरेक कोर्समा समावेश",
    features: ["रेकर्ड गरिएका भिडियो पाठ", "लाइभ कक्षा", "अध्याय अनुसार नोट्स", "अध्याय MCQ र परीक्षा", "समाधानसहित मोडेल सेट", "जुनसुकै बेला SikAI लाई सोध्नुहोस्"],
    totals: { subjects: "विषय", chapters: "अध्याय", videos: "भिडियो पाठ", notes: "नोट्स" },
  },
  schools: {
    title: "Note Swift लाई आफ्नो विद्यालयमा ल्याउनुहोस्।",
    lead: "प्रमुख र शिक्षकका लागि हाजिरी, असाइनमेन्ट, परीक्षा र रिपोर्ट, अनि हरेक विद्यार्थीका लागि विद्यार्थी एप।",
    secondary: "साझेदारी कसरी हुन्छ",
    features: ["हाजिरी", "असाइनमेन्ट", "अनलाइन परीक्षा", "रिपोर्ट"],
  },
  stories: {
    eyebrow: "विद्यार्थीका अनुभव",
    title: "उनीहरूकै शब्दमा।",
    prev: "अघिल्लो अनुभव",
    next: "अर्को अनुभव",
    items: [
      { quote: "पहिले म जुनसुकै भिडियो हेर्थें र अझै अलमलिन्थें। हरेक अध्यायका पाठ, नोट्स र प्रश्न एकै ठाउँमा हुँदा मेरो दोहोर्याइ धेरै सजिलो भयो।", name: "आयुषा श्रेष्ठ", role: "कक्षा १२ विज्ञान, काठमाडौं" },
      { quote: "SikAI ले उत्तर मात्र दिँदैन, चरणहरू बुझाउँछ। अब अर्को भौतिकशास्त्रको प्रश्न म आफैं हल गर्न सक्छु।", name: "बिबेक थापा", role: "कक्षा ११ विज्ञान, पोखरा" },
      { quote: "अध्याय परीक्षा साँच्चिकै SEE को प्रश्नपत्र जस्तै लाग्छ। परीक्षाअघि के दोहोर्याउने भनेर अन्ततः थाहा भयो।", name: "सरिता चौधरी", role: "कक्षा १०, धनगढी" },
      { quote: "म विद्यालयमै पाठ डाउनलोड गर्छु र इन्टरनेट ढिलो हुने घरमा हेर्छु। यसैले मेरो पढाइ धेरै बदलियो।", name: "रोजन मगर", role: "कक्षा १०, गोरखा" },
      { quote: "लेखा अब बल्ल बुझिन्छ। शिक्षक बिस्तारै पढाउनुहुन्छ र नोट्स कक्षामा पढ्ने कुरासँग ठ्याक्कै मिल्छ।", name: "प्रशंसा कार्की", role: "कक्षा १२ व्यवस्थापन, विराटनगर" },
      { quote: "बेलुकीको लाइभ कक्षा मेरो ट्युसनसँग मिल्छ। छुटे भने भोलिपल्ट बिहान रेकर्डिङ हुन्छ।", name: "निश्चल अधिकारी", role: "कक्षा ११ विज्ञान, बुटवल" },
    ],
  },
  final: {
    title: "एउटा अध्यायबाट सुरु गर्नुहोस्।",
    lead: "कति सजिलो हुन्छ, आफैं हेर्नुहोस्।",
  },
};

export const home = { en, ne };
